# Generated by Django 2.0 on 2018-06-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=50)),
                ('user_face_0', models.TextField()),
                ('user_face_1', models.TextField()),
                ('user_face_2', models.TextField()),
                ('user_face_3', models.TextField()),
                ('user_face_4', models.TextField()),
            ],
        ),
    ]
