# Generated by Django 2.0 on 2018-06-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transfer', '0003_auto_20180621_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user_phone',
        ),
        migrations.AddField(
            model_name='activity',
            name='a_user_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='b_user_phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='activity',
            name='money',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
